services:
  - type: web
    name: sbs-bomber-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
